
// ***************
// AUTOGENERATED FILE - DO NOT EDIT THIS FILE MANUALLY
// MODIFY AND RUN generateHRTFBinaryIncludes.py TO UPDATE
// ***************

#pragma once
#include <map>
#include <string>
#include <vector>

namespace Spatializer3DTI
{

    extern const std::map<std::string, std::vector<unsigned char>> hrtfBinaries;

}

